export const OPPORTUNITY_STATUSES = {
  PITCHING: 'PITCHING',
  NEGOTIATION: 'NEGOTIATION',
  APPROVAL: 'APPROVAL',
  LEGAL: 'LEGAL',
  SIGNED: 'SIGNED',
  INVOICED: 'INVOICED',
  PAID: 'PAID',
  REJECTED: 'REJECTED'
} as const

export const FLOW_TYPES = {
  OUTBOUND: 'OUTBOUND',
  INBOUND: 'INBOUND'
} as const

export const PROJECT_TYPES = {
  SERIE: 'SERIE',
  PELICULA: 'PELICULA',
  PUBLICIDAD: 'PUBLICIDAD',
  VIDEOJUEGO: 'VIDEOJUEGO'
} as const

export const CLIENT_TYPES = {
  PLATAFORMA: 'PLATAFORMA',
  MARCA: 'MARCA',
  PRODUCTORA: 'PRODUCTORA'
} as const

export const USER_ROLES = {
  SYNC_MANAGER: 'SYNC_MANAGER',
  LEGAL: 'LEGAL',
  ADMIN: 'ADMIN',
  EXECUTIVE: 'EXECUTIVE'
} as const

export const DOCUMENT_TYPES = {
  CONTRATO: 'CONTRATO',
  FACTURA: 'FACTURA',
  APROBACION: 'APROBACION',
  ONE_SHEET: 'ONE_SHEET'
} as const

export const STATUS_COLORS = {
  [OPPORTUNITY_STATUSES.PITCHING]: 'bg-blue-500',
  [OPPORTUNITY_STATUSES.NEGOTIATION]: 'bg-yellow-500',
  [OPPORTUNITY_STATUSES.APPROVAL]: 'bg-orange-500',
  [OPPORTUNITY_STATUSES.LEGAL]: 'bg-purple-500',
  [OPPORTUNITY_STATUSES.SIGNED]: 'bg-green-500',
  [OPPORTUNITY_STATUSES.INVOICED]: 'bg-indigo-500',
  [OPPORTUNITY_STATUSES.PAID]: 'bg-emerald-500',
  [OPPORTUNITY_STATUSES.REJECTED]: 'bg-red-500'
} as const

export const FLOW_COLORS = {
  [FLOW_TYPES.OUTBOUND]: 'bg-blue-500',
  [FLOW_TYPES.INBOUND]: 'bg-red-500'
} as const

export const STATUS_LABELS = {
  [OPPORTUNITY_STATUSES.PITCHING]: 'Pitching',
  [OPPORTUNITY_STATUSES.NEGOTIATION]: 'Negociación',
  [OPPORTUNITY_STATUSES.APPROVAL]: 'Aprobación',
  [OPPORTUNITY_STATUSES.LEGAL]: 'Legal',
  [OPPORTUNITY_STATUSES.SIGNED]: 'Firmado',
  [OPPORTUNITY_STATUSES.INVOICED]: 'Facturado',
  [OPPORTUNITY_STATUSES.PAID]: 'Pagado',
  [OPPORTUNITY_STATUSES.REJECTED]: 'Rechazado'
} as const

export const FLOW_LABELS = {
  [FLOW_TYPES.OUTBOUND]: 'Outbound',
  [FLOW_TYPES.INBOUND]: 'Inbound'
} as const

export const PROJECT_TYPE_LABELS = {
  [PROJECT_TYPES.SERIE]: 'Serie',
  [PROJECT_TYPES.PELICULA]: 'Película',
  [PROJECT_TYPES.PUBLICIDAD]: 'Publicidad',
  [PROJECT_TYPES.VIDEOJUEGO]: 'Videojuego'
} as const

export const CLIENT_TYPE_LABELS = {
  [CLIENT_TYPES.PLATAFORMA]: 'Plataforma',
  [CLIENT_TYPES.MARCA]: 'Marca',
  [CLIENT_TYPES.PRODUCTORA]: 'Productora'
} as const

export const USER_ROLE_LABELS = {
  [USER_ROLES.SYNC_MANAGER]: 'Sync Manager',
  [USER_ROLES.LEGAL]: 'Legal',
  [USER_ROLES.ADMIN]: 'Admin',
  [USER_ROLES.EXECUTIVE]: 'Executive'
} as const

export const DOCUMENT_TYPE_LABELS = {
  [DOCUMENT_TYPES.CONTRATO]: 'Contrato',
  [DOCUMENT_TYPES.FACTURA]: 'Factura',
  [DOCUMENT_TYPES.APROBACION]: 'Aprobación',
  [DOCUMENT_TYPES.ONE_SHEET]: 'One Sheet'
} as const

export const STATE_TRANSITIONS = {
  [OPPORTUNITY_STATUSES.PITCHING]: [OPPORTUNITY_STATUSES.NEGOTIATION, OPPORTUNITY_STATUSES.REJECTED],
  [OPPORTUNITY_STATUSES.NEGOTIATION]: [OPPORTUNITY_STATUSES.APPROVAL, OPPORTUNITY_STATUSES.LEGAL, OPPORTUNITY_STATUSES.REJECTED],
  [OPPORTUNITY_STATUSES.APPROVAL]: [OPPORTUNITY_STATUSES.LEGAL, OPPORTUNITY_STATUSES.REJECTED],
  [OPPORTUNITY_STATUSES.LEGAL]: [OPPORTUNITY_STATUSES.SIGNED, OPPORTUNITY_STATUSES.REJECTED],
  [OPPORTUNITY_STATUSES.SIGNED]: [OPPORTUNITY_STATUSES.INVOICED],
  [OPPORTUNITY_STATUSES.INVOICED]: [OPPORTUNITY_STATUSES.PAID],
  [OPPORTUNITY_STATUSES.PAID]: [],
  [OPPORTUNITY_STATUSES.REJECTED]: [OPPORTUNITY_STATUSES.PITCHING]
} as const

export const URGENCY_LEVELS = {
  CRITICAL: 'critical',    // INBOUND, deadlines < 24h
  HIGH: 'high',           // Deadlines < 48h
  MEDIUM: 'medium',       // Deadlines < 1 semana
  LOW: 'low'              // Sin deadline o > 1 semana
} as const

export const URGENCY_COLORS = {
  [URGENCY_LEVELS.CRITICAL]: 'bg-red-500',
  [URGENCY_LEVELS.HIGH]: 'bg-orange-500',
  [URGENCY_LEVELS.MEDIUM]: 'bg-yellow-500',
  [URGENCY_LEVELS.LOW]: 'bg-green-500'
} as const

